version: '3.2'
services:
  postgresql:
    restart: 'always'
    ports:
      - '{{flac.port}}:5432'
    environment:
      - "{{flac}}_DB_USER={{flac.user}}"
      - "{{flac}}_DB_PASSWORD={{flac.password}}"
      - "{{flac}}_DB_DATABASE={{flac.database}}"
      - "POSTGRES_PASSWORD=password"
    build: './flac'
    container_name: {{flab}}_{{flac}}
    restart: unless-stopped